import {
    StandardButton,
    Button,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { CustomButton } from "custom-button.slint";
import { Logic } from "../logic.slint";

export component AboutPopup inherits PopupWindow {
    close-policy: PopupClosePolicy.close-on-click;
    preferred-width: 500px;
    preferred-height: 500px;

    Rectangle {
        height: 100%;
        width: 100%;
        border-radius: 10px;
        background: #bab9b6;

        VerticalLayout {
            alignment: LayoutAlignment.start;
            padding: 4px;

            Button {
                text: "created by zzz";
                colorize-icon: true;
                icon: @image-url("../assets/github.png");
                clicked => {
                    Logic.open_git()
                }
            }

            Text {
                color: black;
                font-size: 17px;
                text: "app version: " + Logic.app_version;
            }
        }
    }
}
