import { Button, GridBox, ListView, VerticalBox } from "std-widgets.slint";
import { PackageInfo, Logic } from "../logic.slint";
import { CustomButton } from "custom_button.slint";

export component PkgList inherits ListView {
    height: 100%;
    width: 100%;
    
    for pkg in Logic.pkgs_info: HorizontalLayout {
    
        padding: 0px;
        
        CustomButton {
            font-size: 13px;
            width: 100%; 
            text: pkg.package-base;
            clicked => {
                Logic.pkg_selected = pkg;
                Logic.pkg_selected_callback(pkg.package-base);
                Logic.pkg_info_is_visible = true;
            }
        }
    }
}
