import { Button, GridBox, ListView, VerticalBox } from "std-widgets.slint";
import { PackageInfo } from "../logic.slint";

export component PkgList inherits ListView {
    height: 100%;
    
    in-out property <[PackageInfo]> pkgs_info;
    
    
    callback pkg_selected(PackageInfo);
    callback pkg_info_is_visible(bool);
    
    for pkg in pkgs_info: HorizontalLayout {
        padding: 0px;
        in-out property <color> back;
        Rectangle {
            border-width: 0.2px;
            border-radius: 10px;
            background: area.has-hover ? gray.transparentize(0.8) : back;

            animate background { duration: 250ms; }
            Text {
                font-size: 15px;
                text: pkg.package-base;
            }

            area := TouchArea {
                clicked => {
                    pkg_selected(pkg);
                    pkg_info_is_visible(true);
                }
            }
        }
    }
}
