import { HorizontalBox, VerticalBox, LineEdit, Button } from "std-widgets.slint";


export component PkgSearch inherits HorizontalBox {
    padding: 5px;
    height: 35px;
    alignment: LayoutAlignment.center;

    in-out property <string> pkg_name;
    in-out property <color> back;

    callback search_pkg(string);
    
    LineEdit {
        width: 700px;
        height: 33px;
        font-size: 15px;
        placeholder-text: "Search Packages";
    
        accepted(text) => {
            search_pkg(text);
        }
        edited(text) => {
            pkg_name = text; 
        }
    }
    
    Rectangle {
        width: 30px; 
        height: 33px;
        border-width: 0.1px;
        border-radius: 8px;
        background: area.has-hover ? white.transparentize(0.8) : back;
        
        animate background {
            duration: 250ms;
        }

        Image {
            colorize: white;
            source: @image-url("../assets/search.png");            
        }
        
        area := TouchArea {
            clicked => {
                search_pkg(pkg_name);
            }
        }
    }
}
