import { HorizontalBox, VerticalBox, LineEdit, Button } from "std-widgets.slint";
import { CustomButton } from "custom_button.slint";


export component PkgSearch inherits HorizontalBox {
    padding: 0px;
    height: 35px;
    alignment: LayoutAlignment.center;

    in-out property <string> pkg_name;
    in-out property <color> back;

    callback search_pkg(string);
    
    LineEdit {
        width: 700px;
        font-size: 15px;
        placeholder-text: "Search Packages";
        input-type: InputType.text;
        
        accepted(text) => {
            search_pkg(text);
        }
        edited(text) => {
            pkg_name = text; 
        }
    }
    
    
    CustomButton {
        icon: @image-url("../assets/search.png"); 
        clicked => {
            search_pkg(pkg_name);
        }
    }
}
