import { TextEdit, Button, VerticalBox, LineEdit } from "std-widgets.slint";
import { Terminal } from "terminal.slint";
import { Theme, PackageInfo, Logic } from "../../logic.slint";
import { CustomButton } from "../custom_button.slint";

export component PkgInfo inherits VerticalBox {
    width: 50%;
    padding: 0px;
    spacing: 5px;
    visible: Logic.pkg_info_is_visible;

    in-out property <string> terminal_output;

    callback send_terminal_input(string);

    HorizontalLayout {
        spacing: 10px;

        Text {
            color: Theme.text_color;
            font-size: 19px;
            height: 28px;
            text: Logic.pkg_selected.package-base;
        }

        if Logic.pkg_selected.is-installed == true: CustomButton {
            text: "Uninstall";
            font-size: 15px;
            width: 70px;
            clicked => {
                Logic.terminal_is_visible = true;
                Logic.uninstall_pkg(Logic.pkg_selected.package-base);
            }
        }

        if Logic.pkg_selected.is-installed == false: CustomButton {
            text: "Install";
            font-size: 15px;
            width: 60px;
            clicked => {
                Logic.terminal_is_visible = true;
                Logic.install_pkg(Logic.pkg_selected.package-base);
            }
        }

        CustomButton {
            icon: @image-url("../../assets/square-terminal.png");
            width: 30px;
            background: gray;
            clicked => {
                Logic.terminal_is_visible = !Logic.terminal_is_visible;
            }
        }
    }

    Text {
        color: Theme.text_color;
        font-size: 15px;
        height: 28px;
        text: "Version: " + Logic.pkg_selected.version;
    }

    Text {
        color: Theme.text_color;
        font-size: 15px;
        height: 28px;
        text: "Maintainer: " + Logic.pkg_selected.maintainer;
    }

    Text {
        color: Theme.text_color;
        font-size: 15px;
        height: 28px;
        text: "Repository: " + Logic.pkg_selected.repo;
    }

    TextEdit {
        text: Logic.pkg_selected.description;
        font-size: 15px;
        read-only: true;
        height: 20%;
    }

    Terminal {}
}
