import { TextEdit, Button, VerticalBox, LineEdit } from "std-widgets.slint";
import { Terminal } from "terminal.slint";
import { Theme } from "../../Theme.slint";
import { CustomButton } from "../custom_button.slint";

export component PkgInfo inherits VerticalBox {
    width: 50%;
    padding: 0px;
    spacing: 5px;
    visible: pkg_info_is_visible;

    in-out property <bool> pkg_info_is_visible: false;
    in-out property <string> package-base;
    in-out property <string> version;
    in-out property <string> description;
    in-out property <string> maintainer;
    in-out property <string> terminal_output;
    in-out property <bool> pkg_is_installed;
    in-out property <string> repository;
    in-out property <bool> terminal_is_visible;
    in-out property <string> log;

    callback copy_log(string);
    callback install_pkg(string);
    callback uninstall_pkg(string);
    callback send_terminal_input(string);

    HorizontalLayout {
        spacing: 10px;
        
        Text {
            color: Theme.text_color; 
            font-size: 19px;
            height: 28px;
            text: package-base;
        }

        if pkg_is_installed == true: CustomButton {
            text: "Uninstall";
            font-size: 15px;
            width: 70px;
            clicked => {
                terminal_is_visible = true;
                uninstall_pkg(package-base);
            }
        }
        
        if pkg_is_installed == false: CustomButton {
            text: "Install";
            font-size: 15px;
            width: 60px;
            clicked => {
                terminal_is_visible = true;
                install_pkg(package-base);
            }
        }

        CustomButton {
            icon: @image-url("../../assets/square-terminal.png");
            width: 30px;
            background: gray;
            clicked => {
                terminal_is_visible = !terminal_is_visible;
            }
        }
    }

    Text {
        color: Theme.text_color;
        font-size: 15px;
        height: 28px;
        text: "Version: " + version;
    }

    Text {
        color: Theme.text_color;
        font-size: 15px;
        height: 28px;
        text: "Maintainer: " + maintainer;
    }
    
    Text {
        color: Theme.text_color;
        font-size: 15px;
        height: 28px;
        text: "Repository: " + repository;
    }

    TextEdit {
        text: description;
        font-size: 15px;
        read-only: true;
        height: 20%;
    }
    
    Terminal {
        output: terminal_output;
        visible: terminal_is_visible;
        log_ter: log;

        send_terminal_input(text) => {
            send_terminal_input(text);
        }

        copy_log => {
            copy_log(log);
        }
    }
}