import {
    VerticalBox,
    TextEdit,
    LineEdit,
    ScrollView,
    SpinBox,
    Button,
    HorizontalBox,
} from "std-widgets.slint";


export component Terminal inherits VerticalBox {
    height: 400px;
    in-out property <string> output;
    in-out property <string> log_ter;
    callback copy_log(string);
    callback send_terminal_input(string);

    TextEdit {
        text: output;
        font-size: 15px;
        read-only: true;
    }

    HorizontalBox {
        LineEdit {
            accepted(text) => {
                send_terminal_input(text);
            }
        }

        Button {
            text: "Copy Log";
            clicked => {
                copy_log(log_ter);
            }
        }
    }
}
