import {
    VerticalBox,
    TextEdit,
    LineEdit,
    ScrollView,
    SpinBox,
    Button,
    HorizontalBox,
} from "std-widgets.slint";


export component Terminal inherits VerticalBox {
    height: 400px;
    padding: 0px;
    in-out property <string> output;
    callback send_terminal_input(string);

    TextEdit {
        text: output;
        font-size: 15px;
        read-only: true;
        changed text => {
            self.viewport-y = -99999.0px;
        }
    }

    HorizontalBox {
        LineEdit {
            font-size: 15px; 
            accepted(text) => {
                send_terminal_input(text);
            }
        }
    }
}
