import { PackagesInfo } from "logic.slint";
import { Button, VerticalBox, GridBox, TextEdit, LineEdit, ScrollView, HorizontalBox, ListView } from "std-widgets.slint";
import { PkgSearch } from "pkg-search.slint";
import { PkgList } from "pkg-list.slint";
import { PkgInfo } from "pkg-info.slint";


export global Logic {
    callback search_pkg(string);
    callback install_pkg(pkg_name:string);
    in-out property <string> pkg_name;
    in-out property <[PackagesInfo]> pkgs_info;
    in-out property <PackagesInfo> pkg_selected;
    in-out property <bool> pkg_info_is_visible;
}

export component AppWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    VerticalBox {
        HorizontalBox {
            Text {
                font-size: 18px; 
                text: "Search Package";
            }
            PkgSearch {
                search_pkg(name) => {
                    Logic.pkg_name = name;
                    Logic.search_pkg(name);
                    name
                };
            } 
        }
        
        
        
        GridBox {
            width: 100%; 
            height: 100%;
            
            PkgList {
                pkg_info_is_visible: Logic.pkg_info_is_visible;
                pkg_selected: Logic.pkg_selected;
                pkgs_info: Logic.pkgs_info;
            }
            PkgInfo {}
        }
        
    }
}


