import { PackageInfo } from "logic.slint";

import {
    Button,
    VerticalBox,
    GridBox,
    TextEdit,
    LineEdit,
    ScrollView,
    HorizontalBox,
    ListView,
    Button,
    Spinner,
    StandardButton,
} from "std-widgets.slint";


import { PkgSearch } from "components/pkg-search.slint";
import { PkgList } from "components/pkg-list.slint";
import { PkgInfo } from "components//pkg_info/pkg_info.slint";
import { AboutPopup } from "components/about-popup.slint";
import { CustomButton } from "components/custom_button.slint";
import { SettingsPage } from "settings-page.slint";
import { Theme, Logic } from "logic.slint";
import { SearchPackagePage } from "search-package-page.slint";
export { Theme, Logic }

export component AppWindow inherits Window {
    title: "linux-tool";
    preferred-width: 800px;
    preferred-height: 800px;
    background: Theme.background;
    
    if Logic.window_config_open: SettingsPage {
        visible: Logic.window_config_open;
    }
    
    SearchPackagePage {}
}
