import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { CustomButton } from "components/custom_button.slint";


export component WindowConfig inherits VerticalBox {

    visible: open_window_config; 

    in-out property <bool> open_window_config;
    callback open_window_home(bool);
    
    HorizontalBox {
    
        Text {
            text: "zzzz"; 
        }
        CustomButton {
            icon: @image-url("assets/menu-hamburguer.png");
            
            clicked => {
                open_window_config = false;
                open_window_home(true);
            }
        }
    }
    
}