import { Button, GridBox, ListView } from "std-widgets.slint";
import { PackagesInfo } from "logic.slint";

export component PkgList inherits ListView {
    height: 92%; 
    in-out property <[PackagesInfo]> pkgs_info;
    in-out property <PackagesInfo> pkg_selected;
    in-out property <bool> pkg_info_is_visible;
    for pkg in pkgs_info: GridBox {
        padding: 1px;
        
        Button {
            text: pkg.package-base;
            clicked => {
                pkg_selected = pkg;
                pkg_info_is_visible = true;                
            }
        }
    }
}