import { TextEdit, Button, VerticalBox } from "std-widgets.slint";

component CustomButton inherits Rectangle {
    callback clicked();
    property <color> default_back_color;
    border-radius: 8px;
    border-width: 0.2px;
    
    in-out property <string> text;
    
    
    
    background: area.has-hover ? gray.transparentize(0.8) : default_back_color;
    
    Text {
        font-size: 14px;
        text: text; 
    }
    
    area := TouchArea {
        clicked => {
            clicked()
        }
    }
}



export component PkgInfo inherits VerticalBox {
    width: 50%;
    padding: 3px;
    visible: is_visible;
    
    
    in-out property <bool> is_visible: false;
    in-out property <string> package-base;
    in-out property <string> version;
    in-out property <string> description;
    in-out property <string> maintainer;

    callback install_pkg(string);
    
    HorizontalLayout {
        spacing: 10px;
    
        Text {
            font-size: 19px;
            height: 28px;
            text: package-base; 
        }
        
        CustomButton {
            text: "Install";
            clicked => {
                install_pkg(package-base);
            }
        }
        
        CustomButton {
            text: "Uninstall";
            clicked => {
                install_pkg(package-base)
            }
        }
        
    }
    
    
    Text {        
        font-size: 15px;
        height: 28px;
        text: "Version: " + version; 
    }
    
    Text {
        font-size: 15px;
        height: 28px;
        text: "Maintainer: " + maintainer;
    }
    
    TextEdit {
        text: description;
        font-size: 15px;
        enabled: false;
    }
}
