import { LineEdit, VerticalBox } from "std-widgets.slint";

export component PkgSearch inherits VerticalBox {
    width: 100%; 
    height: 35px;
    padding: 0px;
    callback search_pkg(string) -> string;
    LineEdit {
        width: 600px;
        height: 33px;
        font-size: 15px;
        placeholder-text: "Package Name";
        in-out property <string> prop;
        accepted(text) => {
            search_pkg(text);
        }
        
    }
}