import { TextEdit, Button, VerticalBox } from "std-widgets.slint";

component CustomButton inherits Rectangle {
    callback clicked();
    property <color> default_back_color;
    in-out property <string> text;
    in-out property <image> icon;
    

    border-radius: 8px;
    border-width: 0.2px;

    
    
    background: area.has-hover ? gray.transparentize(0.8) : default_back_color;
    
    Image {
        source: icon;
    }

    Text {
        font-size: 14px;
        text: text; 
    }
    
    area := TouchArea {
        clicked => {
            clicked()
        }
    }
}


component Terminal {
    height: 400px;
    in-out property <bool> terminal_is_visible: false;
    in-out property <string> output;

    VerticalBox {
        TextEdit {
            enabled: false;
            text: output;
        }
    }
}


export component PkgInfo inherits VerticalBox {
    width: 50%;
    padding: 3px;
    visible: pkg_info_is_visible;
    
    
    in-out property <bool> pkg_info_is_visible: false;
    in-out property <string> package-base;
    in-out property <string> version;
    in-out property <string> description;
    in-out property <string> maintainer;
    in-out property <string> terminal_output;

    
    callback install_pkg(string);
    
    HorizontalLayout {
        spacing: 10px;
    
        Text {
            font-size: 19px;
            height: 28px;
            text: package-base; 
        }
        
        CustomButton {
            text: "Install";
            clicked => {
                install_pkg(package-base);
            }
        }
        
        CustomButton {
            icon: @image-url("assets/square-terminal.png");
            width: 30px;
            background: gray;
            clicked => {
                debug(terminal_output);
            }
        }
        
    }
    
    
    Text {        
        font-size: 15px;
        height: 28px;
        text: "Version: " + version; 
    }
    
    Text {
        font-size: 15px;
        height: 28px;
        text: "Maintainer: " + maintainer;
    }
    
    TextEdit {
        text: description;
        font-size: 15px;
        enabled: false;
    }

    Terminal {
        output: terminal_output;
    }
}
