import { PkgInfo } from "components/pkg_info/pkg_info.slint";
import { PkgList } from "components/pkg-list.slint";
import { GridBox, Spinner, HorizontalBox } from "std-widgets.slint";
import { PkgSearch } from "components/pkg-search.slint";
import { CustomButton } from "components/custom_button.slint";
import { Logic } from "logic.slint";

export component SearchPackagePage inherits VerticalLayout {
    visible: Logic.window_main_open;
    padding: 5px;

    HorizontalBox {
        padding: 0px;
        height: 40px;
        
        CustomButton {
            icon: @image-url("assets/menu-hamburguer.png");
    
            clicked => {
                Logic.window_main_open = false;
                Logic.window_config_open = true;
            }
        }
    
        PkgSearch {}
    }
    
    if Logic.loading_pkgs: HorizontalBox {
        alignment: LayoutAlignment.center;
    
        Spinner {
            height: 50px;
            width: 50px;
            indeterminate: true;
        }
    }
    
    Rectangle {
        if Logic.pkgs_info.length >= 1: GridBox {
            width: 100%;
    
            Rectangle {
                border-color: black;
                border-width: 0.8px;
                border-radius: 8px;
    
                PkgList {}
            }
    
            PkgInfo {}
            
        }
    }
}