import { PkgInfo } from "components/pkg_info/pkg_info.slint";
import { PkgList } from "components/pkg-list.slint";
import { GridBox, Spinner, HorizontalBox } from "std-widgets.slint";
import { PkgSearch } from "components/pkg-search.slint";
import { CustomButton } from "components/custom_button.slint";
import { Logic } from "logic.slint";

export component SearchPackagePage inherits VerticalLayout {
    visible: Logic.window_main_open;
    padding: 5px;

    HorizontalBox {
        padding: 0px;
        height: 40px;
        
        CustomButton {
            icon: @image-url("assets/menu-hamburguer.png");
    
            clicked => {
                Logic.window_main_open = false;
                Logic.window_config_open = true;
            }
        }
    
        PkgSearch {}
    }
    
    if Logic.loading_pkgs: HorizontalBox {
        alignment: LayoutAlignment.center;
    
        Spinner {
            height: 50px;
            width: 50px;
            indeterminate: true;
        }
    }
    
    Rectangle {
        if Logic.pkgs_info.length >= 1: GridBox {
            width: 100%;
    
            Rectangle {
                border-color: black;
                border-width: 0.8px;
                border-radius: 8px;
    
                PkgList {
                    pkgs_info: Logic.pkgs_info;
    
                    pkg_selected(pkg-selected) => {
                        Logic.pkg_selected = pkg-selected;
                        Logic.pkg_selected_callback(pkg-selected.package-base);
                    }
    
                    pkg_info_is_visible(is) => {
                        Logic.pkg_info_is_visible = is;
                    }
                }
            }
    
            PkgInfo {
                pkg_info_is_visible: Logic.pkg_info_is_visible;
                package-base: Logic.pkg_selected.package-base;
                version: Logic.pkg_selected.version;
                description: Logic.pkg_selected.description;
                maintainer: Logic.pkg_selected.maintainer;
                terminal_output: Logic.terminal_output;
                pkg_is_installed: Logic.pkg_selected.is-installed;
                repository: Logic.pkg_selected.repo;
                terminal_is_visible: Logic.terminal_is_visible;
    
                send_terminal_input(text) => {
                    Logic.terminal_input = text;
                    Logic.send_terminal_input(text);
                }
    
                install_pkg => {
                    Logic.install_pkg(Logic.pkg_selected.package-base);
                }
    
                uninstall_pkg => {
                    Logic.uninstall_pkg(Logic.pkg_selected.package-base);
                }
            }
        }
    }
}