import { PkgInfo } from "components/pkg-info/pkg-info.slint";
import { PkgList } from "components/pkg-list.slint";
import { GridBox, Spinner, HorizontalBox } from "std-widgets.slint";
import { PkgSearch } from "components/pkg-search.slint";
import { CustomButton } from "components/custom-button.slint";
import { Logic, Pages } from "logic.slint";

export component SearchPackagePage inherits VerticalLayout {
    visible: Logic.current_page == Pages.SearchPackagesPage;
    height: 100%;
    padding: 5px;
    HorizontalBox {
        padding: 0px;
        height: 40px;

        PkgSearch { }
    }

    if Logic.loading_pkgs: HorizontalBox {
        alignment: LayoutAlignment.center;

        Spinner {
            height: 50px;
            width: 50px;
            indeterminate: true;
        }
    }

    Rectangle {
        if Logic.pkgs_info.length >= 1: GridBox {
            width: 100%;
            padding: 10px;
            
            VerticalLayout {
                height: 95%;
                Rectangle {
                    border-color: black;
                    border-width: 0.8px;
                    border-radius: 8px;
                    PkgList { }
                }
            }
            
            if !Logic.pkg_selected.package-base.is-empty: VerticalLayout {
                width: 50%;
                height: 95%;
                padding: 0px;
                alignment: LayoutAlignment.start;
                Rectangle {
                    border-color: black;
                    border-width: 0.8px;
                    border-radius: 8px;
                    height: 100%;

                    HorizontalBox {
                        padding: 0px;
                        alignment: LayoutAlignment.start;
                        PkgInfo { }

                    }
                }
            }
        }
    }
}
