import {
    VerticalBox,
    HorizontalBox,
    ComboBox,
    Switch,
    AboutSlint,
    Button,
    StandardButton,
} from "std-widgets.slint";
import { CustomButton } from "components/custom-button.slint";
import { Theme, Logic, Pages } from "logic.slint";
import { AboutPopup } from "components/about-popup.slint";

export component SettingsPage inherits VerticalBox {
    visible: Logic.current_page == Pages.SettingsPage;
    padding: 5px;

    Switch {
        height: 22px;
        text: Theme.dark_mode ? "Dark" : "Light";
        checked: Theme.dark_mode ? true : false;
        toggled => {
            Theme.dark_mode = Theme.dark_mode ? false : true;
            Theme.dark_mode_callback(Theme.dark_mode)
        }
    }

    pop := AboutPopup {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }

    CustomButton {
        width: 70px;
        height: 37px;
        text: "About";
        font-size: 17px;
        border-color: #939995;
        border-width: 0.8px;
        border-radius: 10px;
        clicked => {
            pop.show();
        }
    }
}
