import { VerticalBox, HorizontalBox, ComboBox, Switch } from "std-widgets.slint";
import { CustomButton } from "components/custom_button.slint";


export component WindowConfig inherits VerticalBox {
    visible: open_window_config; 
    padding: 5px;
    
    in-out property <bool> open_window_config;
    in-out property <bool> current_theme;
    
    callback open_main_window(main: bool, config: bool);
    callback dark_mode(bool);
    
    CustomButton {

        icon: @image-url("assets/angulo-esquerdo.png");
        
        clicked => {
            open_main_window(true, false);
        }
    }

    Switch {
        height: 22px;
        text: current_theme ? "Dark" : "Light";
        checked: current_theme ? true : false;
        toggled => {
            dark_mode(current_theme ? false : true);
        }
    } 
}