import { VerticalBox, HorizontalBox, ComboBox, Switch, AboutSlint, Button, StandardButton } from "std-widgets.slint";
import { CustomButton } from "components/custom_button.slint";

export component WindowConfig inherits VerticalBox {
    visible: open_window_config; 
    padding: 5px;
    
    in-out property <bool> open_window_config;
    in-out property <bool> current_theme;
    
    callback open_main_window(main: bool, config: bool);
    callback dark_mode(bool);
    
    CustomButton {

        icon: @image-url("assets/angulo-esquerdo.png");
        
        clicked => {
            open_main_window(true, false);
        }
    }

    Switch {
        height: 22px;
        text: current_theme ? "Dark" : "Light";
        checked: current_theme ? true : false;
        toggled => {
            dark_mode(current_theme ? false : true);
        }
    }
    
    // popup := PopupWindow {
    //     Rectangle {
    //         width: 100%;
    //         height: 100%;
    //         background: gray;
    //         border-color: #82807a;
    //         border-width: 0.8px;
    //         border-radius: 8px;
            
    //         VerticalBox {
                
    //         }
            
    //     }
    //     height: 600px;
    //     width: 600px;
    //     x: (parent.width - self.width) / 2;
    //     y:  (parent.height - self.height) / 2;
        
    // }
    
    // Button {
    //     text: "About";
    //     width: 60px;
    //     height: 50px;
    //     clicked => {
    //         popup.show()
    //     }
    // }
    
    
}


