import { VerticalBox, HorizontalBox, ComboBox, Switch } from "std-widgets.slint";
import { CustomButton } from "components/custom_button.slint";


export component WindowConfig inherits VerticalBox {
    visible: open_window_config; 
    padding: 5px;
    
    in-out property <bool> open_window_config;
    in-out property <string> current_theme;
    
    callback open_main_window(main: bool, config: bool);
    callback dark_mode(bool);
    
    HorizontalBox {
        padding: 0px;
        CustomButton {

            icon: @image-url("assets/angulo-esquerdo.png");
            
            clicked => {
                open_main_window(true, false);
            }
        }
    }
    
    ComboBox {
        model: ["Dark", "Light"];
        current-value: current_theme;
        selected(current-value) => {
            dark_mode(current-value == "Dark" ? true : false);
        }
    }
    
    
}