import {
    VerticalBox,
    TextEdit,
    LineEdit,
    ScrollView,
    SpinBox,
    Button,
    HorizontalBox,
} from "std-widgets.slint";
import { Logic } from "../../logic.slint";


export component Terminal inherits VerticalBox {
    height: 400px;
    padding: 0px;
    visible: Logic.terminal_is_visible;

    TextEdit {
        text: Logic.terminal_output;
        font-size: 15px;
        read-only: true;
        changed text => {
            self.viewport-y = -99999.0px;
        }
    }

    HorizontalBox {
        LineEdit {
            font-size: 15px;
            accepted(text) => {
                Logic.send_terminal_input(text);
                self.text = "";
            }
        }
    }
}
